/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service Health Check
         * @description Returns service operational status and version
         */
        get: operations["root_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API v1 Health Check
         * @description Returns the current operational status and version of the API.
         */
        get: operations["api_v1_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Market Data
         * @description Ingests historical OHLCV data for equities and universe.
         */
        post: operations["api_ingest_data_api_v1_data_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Data Coverage
         * @description Returns stored date ranges and session counts for symbols.
         */
        get: operations["api_get_coverage_api_v1_data_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Universe Constituents
         * @description Returns tickers ranked 101 to 750 with survivorship bias flag.
         */
        get: operations["api_get_universe_api_v1_universe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prices/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Symbol Prices
         * @description Returns historical OHLCV prices for symbol, filtered chronologically.
         */
        get: operations["api_get_prices_api_v1_prices__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indicators/nifty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get NIFTY Benchmark Indicators
         * @description Returns NIFTY benchmark index OHLCV with EMAs (default 50 and 200).
         */
        get: operations["api_get_nifty_indicators_api_v1_indicators_nifty_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indicators/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Symbol Technical Indicators
         * @description Returns historical OHLCV augmented with EMAs (20, 50, 150, 200) and 52W high.
         */
        get: operations["api_get_symbol_indicators_api_v1_indicators__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indicators/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Custom Indicators
         * @description Calculates custom indicators dynamically with given configuration.
         */
        post: operations["api_preview_indicators_api_v1_indicators_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals/screen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Screen Universe for Entry Signals
         * @description Returns point-in-time universe constituent symbols with an active entry signal on the given date (REQ-3.4).
         */
        get: operations["api_screen_signals_api_v1_signals_screen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Symbol Trading Signals
         * @description Returns chronological series of OHLCV bars with technical indicators, filters, and entry/exit signal evaluations (REQ-3.4, REQ-3.5).
         */
        get: operations["api_get_symbol_signals_api_v1_signals__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/size": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Position Size and Risk
         * @description Derives integer share quantity, capital required, stop loss price, and monetary risk amount based on corpus, entry price, stop loss %, and risk % (REQ-4.1, REQ-4.2, REQ-4.3).
         */
        post: operations["api_calculate_risk_size_api_v1_risk_size_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Default Risk Configuration
         * @description Returns baseline strategy risk, stop loss, capital, and cost parameters.
         */
        get: operations["api_get_risk_config_api_v1_risk_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CoverageItem */
        CoverageItem: {
            /**
             * Symbol
             * @description Equity or index ticker symbol
             */
            symbol: string;
            /**
             * First Date
             * @description Earliest available trading session
             */
            first_date?: string | null;
            /**
             * Last Date
             * @description Latest available trading session
             */
            last_date?: string | null;
            /**
             * Rows
             * @description Total number of stored trading sessions
             */
            rows: number;
        };
        /** CoverageResponse */
        CoverageResponse: {
            /**
             * Items
             * @description List of symbol coverage summaries
             */
            items: components["schemas"]["CoverageItem"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description Operational status of the service
             * @default ok
             * @example ok
             */
            status: string;
            /**
             * Version
             * @description Semantic application version
             * @default 0.1.0
             * @example 0.1.0
             */
            version: string;
        };
        /** IndicatorConfigSchema */
        IndicatorConfigSchema: {
            /**
             * Spans
             * @description EMA spans to compute (e.g. [20, 50, 150, 200])
             * @default [
             *       20,
             *       50,
             *       150,
             *       200
             *     ]
             * @example [
             *       20,
             *       50,
             *       150,
             *       200
             *     ]
             */
            spans: number[];
            /**
             * Include High 52W
             * @description Whether to compute rolling 52-week high
             * @default true
             */
            include_high_52w: boolean;
            /**
             * High 52W Lookback
             * @description Lookback window sessions for 52W high calculation
             * @default 252
             * @example 252
             */
            high_52w_lookback: number;
        };
        /** IndicatorItem */
        IndicatorItem: {
            /**
             * Date
             * @description Session date (YYYY-MM-DD)
             */
            date: string;
            /**
             * Open
             * @description Opening price
             */
            open: number;
            /**
             * High
             * @description Highest price during session
             */
            high: number;
            /**
             * Low
             * @description Lowest price during session
             */
            low: number;
            /**
             * Close
             * @description Unadjusted closing price
             */
            close: number;
            /**
             * Adj Close
             * @description Corporate-action adjusted closing price
             */
            adj_close: number;
            /**
             * Volume
             * @description Total trading volume
             */
            volume: number;
            /**
             * Ema 20
             * @description 20-day EMA
             */
            ema_20?: number | null;
            /**
             * Ema 50
             * @description 50-day EMA
             */
            ema_50?: number | null;
            /**
             * Ema 150
             * @description 150-day EMA
             */
            ema_150?: number | null;
            /**
             * Ema 200
             * @description 200-day EMA
             */
            ema_200?: number | null;
            /**
             * High 52W
             * @description 52-week rolling high
             */
            high_52w?: number | null;
            /**
             * Indicators
             * @description Dictionary of dynamic or custom computed indicator values
             */
            indicators?: {
                [key: string]: number | null;
            };
        };
        /** IndicatorPreviewRequest */
        IndicatorPreviewRequest: {
            /**
             * Symbol
             * @description Symbol to compute preview indicators for
             * @default RELIANCE
             * @example RELIANCE
             */
            symbol: string;
            /**
             * Start
             * @description Optional start date (YYYY-MM-DD)
             * @example 2020-01-01
             */
            start?: string | null;
            /**
             * End
             * @description Optional end date (YYYY-MM-DD)
             * @example 2023-12-31
             */
            end?: string | null;
            /** @description Indicator calculation configuration */
            config?: components["schemas"]["IndicatorConfigSchema"];
        };
        /** IndicatorResponse */
        IndicatorResponse: {
            /**
             * Symbol
             * @description Equity or benchmark ticker symbol
             */
            symbol: string;
            /**
             * Count
             * @description Number of indicator bars returned
             */
            count: number;
            /**
             * Indicators
             * @description Chronological series of indicator-augmented OHLCV bars
             */
            indicators: components["schemas"]["IndicatorItem"][];
        };
        /** IngestRequest */
        IngestRequest: {
            /**
             * Start
             * @description Start date for data ingestion in YYYY-MM-DD format
             * @example 2020-01-01
             */
            start: string;
            /**
             * End
             * @description End date for data ingestion in YYYY-MM-DD format
             * @example 2024-01-01
             */
            end: string;
            /**
             * Symbols
             * @description Optional list of ticker symbols. Defaults to active universe.
             * @example [
             *       "RELIANCE",
             *       "HDFCBANK",
             *       "INFY"
             *     ]
             */
            symbols?: string[] | null;
        };
        /** IngestResponse */
        IngestResponse: {
            /**
             * Job Id
             * @description Unique ingestion job execution ID
             */
            job_id: string;
            /**
             * Status
             * @description Job execution status (completed, partial, failed)
             */
            status: string;
            /**
             * Symbols Ingested
             * @description Number of symbols successfully processed
             */
            symbols_ingested: number;
            /**
             * Rows Ingested
             * @description Total new price rows inserted into database
             */
            rows_ingested: number;
            /**
             * Errors
             * @description List of non-fatal ingestion warnings or errors
             * @default []
             */
            errors: string[];
        };
        /** PriceItem */
        PriceItem: {
            /**
             * Date
             * @description Session date (YYYY-MM-DD)
             */
            date: string;
            /**
             * Open
             * @description Opening price
             */
            open: number;
            /**
             * High
             * @description Highest price during session
             */
            high: number;
            /**
             * Low
             * @description Lowest price during session
             */
            low: number;
            /**
             * Close
             * @description Unadjusted closing price
             */
            close: number;
            /**
             * Adj Close
             * @description Corporate-action adjusted closing price
             */
            adj_close: number;
            /**
             * Volume
             * @description Total trading volume
             */
            volume: number;
        };
        /** PricesResponse */
        PricesResponse: {
            /**
             * Symbol
             * @description Equity ticker symbol
             */
            symbol: string;
            /**
             * Count
             * @description Number of sessions returned
             */
            count: number;
            /**
             * Prices
             * @description Chronological series of OHLCV bars
             */
            prices: components["schemas"]["PriceItem"][];
        };
        /** RiskConfigResponse */
        RiskConfigResponse: {
            /**
             * Corpus
             * @description Default portfolio starting corpus in INR
             * @default 500000
             */
            corpus: number;
            /**
             * Risk Pct
             * @description Default risk percentage per trade (2%)
             * @default 0.02
             */
            risk_pct: number;
            /**
             * Stop Loss Pct
             * @description Default stop loss percentage (7%)
             * @default 0.07
             */
            stop_loss_pct: number;
            /**
             * Lot Size
             * @description Default share lot size multiple (1)
             * @default 1
             */
            lot_size: number;
            /**
             * Cost Bps
             * @description Default transaction friction and slippage costs in basis points (10 bps = 0.10%)
             * @default 10
             */
            cost_bps: number;
        };
        /** RiskSizeRequest */
        RiskSizeRequest: {
            /**
             * Corpus
             * @description Total account capital / portfolio corpus
             * @example 500000
             */
            corpus: number;
            /**
             * Entry
             * @description Proposed trade entry price per share
             * @example 100
             */
            entry: number;
            /**
             * Sl Pct
             * @description Stop loss percentage distance from entry (default 0.07)
             * @default 0.07
             * @example 0.07
             */
            sl_pct: number;
            /**
             * Risk Pct
             * @description Maximum account risk percentage per trade (default 0.02)
             * @default 0.02
             * @example 0.02
             */
            risk_pct: number;
            /**
             * Lot Size
             * @description Minimum lot size multiple (default 1)
             * @default 1
             * @example 1
             */
            lot_size: number;
        };
        /** RiskSizeResponse */
        RiskSizeResponse: {
            /**
             * Qty
             * @description Derived integer position size / share quantity
             */
            qty: number;
            /**
             * Capital Required
             * @description Total capital required for this position (qty * entry)
             */
            capital_required: number;
            /**
             * Sl Price
             * @description Stop loss price level (entry * (1 - sl_pct))
             */
            sl_price: number;
            /**
             * Risk Amount
             * @description Maximum monetary account risk for this trade (corpus * risk_pct)
             */
            risk_amount: number;
        };
        /** ScreenResponse */
        ScreenResponse: {
            /**
             * Date
             * @description Target date for universe screening (YYYY-MM-DD)
             */
            date: string;
            /**
             * Count
             * @description Total number of constituent tickers with entry signal
             */
            count: number;
            /**
             * Symbols
             * @description List of ticker symbols with active entry signals
             */
            symbols: string[];
            /**
             * Survivorship Bias
             * @description True if fallback current list was used due to missing point-in-time constituent records
             */
            survivorship_bias: boolean;
        };
        /** SignalItem */
        SignalItem: {
            /**
             * Date
             * @description Session date (YYYY-MM-DD)
             */
            date: string;
            /**
             * Open
             * @description Opening price
             */
            open: number;
            /**
             * High
             * @description Highest price during session
             */
            high: number;
            /**
             * Low
             * @description Lowest price during session
             */
            low: number;
            /**
             * Close
             * @description Unadjusted closing price
             */
            close: number;
            /**
             * Adj Close
             * @description Corporate-action adjusted closing price
             */
            adj_close: number;
            /**
             * Volume
             * @description Total trading volume
             */
            volume: number;
            /**
             * Ema 20
             * @description 20-day EMA
             */
            ema_20?: number | null;
            /**
             * Ema 50
             * @description 50-day EMA
             */
            ema_50?: number | null;
            /**
             * Ema 150
             * @description 150-day EMA
             */
            ema_150?: number | null;
            /**
             * Ema 200
             * @description 200-day EMA
             */
            ema_200?: number | null;
            /**
             * High 52W
             * @description 52-week rolling high
             */
            high_52w?: number | null;
            /**
             * Regime Ok
             * @description Market regime filter (NIFTY Close > EMA 50 & EMA 200)
             */
            regime_ok: boolean;
            /**
             * Trend Ok
             * @description Stock trend filter (EMA 20 > EMA 50 > EMA 150 > EMA 200)
             */
            trend_ok: boolean;
            /**
             * Near 52W High
             * @description 52W high proximity filter (Close > 0.85 * 52W High)
             */
            near_52w_high: boolean;
            /**
             * Crossover
             * @description EMA20 crossover trigger (Close_T > EMA20_T and Close_T-1 < EMA20_T-1)
             */
            crossover: boolean;
            /**
             * Entry
             * @description Entry signal triggered on bar T for execution on T+1 open
             */
            entry: boolean;
            /**
             * Exit
             * @description Exit signal triggered on bar T (Close_T < EMA20_T)
             */
            exit: boolean;
        };
        /** SignalsResponse */
        SignalsResponse: {
            /**
             * Symbol
             * @description Equity ticker symbol
             */
            symbol: string;
            /**
             * Count
             * @description Number of signal rows returned
             */
            count: number;
            /**
             * Signals
             * @description Chronological series of signal-augmented OHLCV bars
             */
            signals: components["schemas"]["SignalItem"][];
        };
        /** UniverseResponse */
        UniverseResponse: {
            /**
             * Date
             * @description Target date for universe constituent evaluation
             */
            date: string;
            /**
             * Count
             * @description Total number of constituent tickers (ranks 101 to 750)
             */
            count: number;
            /**
             * Tickers
             * @description List of ticker symbols belonging to the universe
             */
            tickers: string[];
            /**
             * Survivorship Bias
             * @description True if fallback current list was used due to missing point-in-time constituent records
             */
            survivorship_bias: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    api_v1_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    api_ingest_data_api_v1_data_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_coverage_api_v1_data_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageResponse"];
                };
            };
        };
    };
    api_get_universe_api_v1_universe_get: {
        parameters: {
            query?: {
                /** @description Target date in YYYY-MM-DD format. Defaults to UTC today. */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_prices_api_v1_prices__symbol__get: {
        parameters: {
            query?: {
                /** @description Optional start date (YYYY-MM-DD) */
                start?: string | null;
                /** @description Optional end date (YYYY-MM-DD) */
                end?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_nifty_indicators_api_v1_indicators_nifty_get: {
        parameters: {
            query?: {
                /** @description Optional start date (YYYY-MM-DD) */
                start?: string | null;
                /** @description Optional end date (YYYY-MM-DD) */
                end?: string | null;
                /** @description Comma-separated list of EMA spans */
                spans?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_symbol_indicators_api_v1_indicators__symbol__get: {
        parameters: {
            query?: {
                /** @description Optional start date (YYYY-MM-DD) */
                start?: string | null;
                /** @description Optional end date (YYYY-MM-DD) */
                end?: string | null;
                /** @description Comma-separated list of EMA spans */
                spans?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_preview_indicators_api_v1_indicators_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndicatorPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_screen_signals_api_v1_signals_screen_get: {
        parameters: {
            query: {
                /** @description Target evaluation date in YYYY-MM-DD format */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_symbol_signals_api_v1_signals__symbol__get: {
        parameters: {
            query?: {
                /** @description Optional start date (YYYY-MM-DD) */
                start?: string | null;
                /** @description Optional end date (YYYY-MM-DD) */
                end?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_calculate_risk_size_api_v1_risk_size_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskSizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskSizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_risk_config_api_v1_risk_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskConfigResponse"];
                };
            };
        };
    };
}
