/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service Health Check
         * @description Returns service operational status and version
         */
        get: operations["root_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API v1 Health Check
         * @description Returns the current operational status and version of the API.
         */
        get: operations["api_v1_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Market Data
         * @description Ingests historical OHLCV data for equities and universe.
         */
        post: operations["api_ingest_data_api_v1_data_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Data Coverage
         * @description Returns stored date ranges and session counts for symbols.
         */
        get: operations["api_get_coverage_api_v1_data_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Universe Constituents
         * @description Returns tickers ranked 101 to 750 with survivorship bias flag.
         */
        get: operations["api_get_universe_api_v1_universe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prices/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Symbol Prices
         * @description Returns historical OHLCV prices for symbol, filtered chronologically.
         */
        get: operations["api_get_prices_api_v1_prices__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indicators/nifty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get NIFTY Benchmark Indicators
         * @description Returns NIFTY benchmark index OHLCV with EMAs (default 50 and 200).
         */
        get: operations["api_get_nifty_indicators_api_v1_indicators_nifty_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indicators/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Symbol Technical Indicators
         * @description Returns historical OHLCV augmented with EMAs (20, 50, 150, 200) and 52W high.
         */
        get: operations["api_get_symbol_indicators_api_v1_indicators__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indicators/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Custom Indicators
         * @description Calculates custom indicators dynamically with given configuration.
         */
        post: operations["api_preview_indicators_api_v1_indicators_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CoverageItem */
        CoverageItem: {
            /**
             * Symbol
             * @description Equity or index ticker symbol
             */
            symbol: string;
            /**
             * First Date
             * @description Earliest available trading session
             */
            first_date?: string | null;
            /**
             * Last Date
             * @description Latest available trading session
             */
            last_date?: string | null;
            /**
             * Rows
             * @description Total number of stored trading sessions
             */
            rows: number;
        };
        /** CoverageResponse */
        CoverageResponse: {
            /**
             * Items
             * @description List of symbol coverage summaries
             */
            items: components["schemas"]["CoverageItem"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description Operational status of the service
             * @default ok
             * @example ok
             */
            status: string;
            /**
             * Version
             * @description Semantic application version
             * @default 0.1.0
             * @example 0.1.0
             */
            version: string;
        };
        /** IndicatorConfigSchema */
        IndicatorConfigSchema: {
            /**
             * Spans
             * @description EMA spans to compute (e.g. [20, 50, 150, 200])
             * @default [
             *       20,
             *       50,
             *       150,
             *       200
             *     ]
             * @example [
             *       20,
             *       50,
             *       150,
             *       200
             *     ]
             */
            spans: number[];
            /**
             * Include High 52W
             * @description Whether to compute rolling 52-week high
             * @default true
             */
            include_high_52w: boolean;
            /**
             * High 52W Lookback
             * @description Lookback window sessions for 52W high calculation
             * @default 252
             * @example 252
             */
            high_52w_lookback: number;
        };
        /** IndicatorItem */
        IndicatorItem: {
            /**
             * Date
             * @description Session date (YYYY-MM-DD)
             */
            date: string;
            /**
             * Open
             * @description Opening price
             */
            open: number;
            /**
             * High
             * @description Highest price during session
             */
            high: number;
            /**
             * Low
             * @description Lowest price during session
             */
            low: number;
            /**
             * Close
             * @description Unadjusted closing price
             */
            close: number;
            /**
             * Adj Close
             * @description Corporate-action adjusted closing price
             */
            adj_close: number;
            /**
             * Volume
             * @description Total trading volume
             */
            volume: number;
            /**
             * Ema 20
             * @description 20-day EMA
             */
            ema_20?: number | null;
            /**
             * Ema 50
             * @description 50-day EMA
             */
            ema_50?: number | null;
            /**
             * Ema 150
             * @description 150-day EMA
             */
            ema_150?: number | null;
            /**
             * Ema 200
             * @description 200-day EMA
             */
            ema_200?: number | null;
            /**
             * High 52W
             * @description 52-week rolling high
             */
            high_52w?: number | null;
            /**
             * Indicators
             * @description Dictionary of dynamic or custom computed indicator values
             */
            indicators?: {
                [key: string]: number | null;
            };
        };
        /** IndicatorPreviewRequest */
        IndicatorPreviewRequest: {
            /**
             * Symbol
             * @description Symbol to compute preview indicators for
             * @default RELIANCE
             * @example RELIANCE
             */
            symbol: string;
            /**
             * Start
             * @description Optional start date (YYYY-MM-DD)
             * @example 2020-01-01
             */
            start?: string | null;
            /**
             * End
             * @description Optional end date (YYYY-MM-DD)
             * @example 2023-12-31
             */
            end?: string | null;
            /** @description Indicator calculation configuration */
            config?: components["schemas"]["IndicatorConfigSchema"];
        };
        /** IndicatorResponse */
        IndicatorResponse: {
            /**
             * Symbol
             * @description Equity or benchmark ticker symbol
             */
            symbol: string;
            /**
             * Count
             * @description Number of indicator bars returned
             */
            count: number;
            /**
             * Indicators
             * @description Chronological series of indicator-augmented OHLCV bars
             */
            indicators: components["schemas"]["IndicatorItem"][];
        };
        /** IngestRequest */
        IngestRequest: {
            /**
             * Start
             * @description Start date for data ingestion in YYYY-MM-DD format
             * @example 2020-01-01
             */
            start: string;
            /**
             * End
             * @description End date for data ingestion in YYYY-MM-DD format
             * @example 2024-01-01
             */
            end: string;
            /**
             * Symbols
             * @description Optional list of ticker symbols. Defaults to active universe.
             * @example [
             *       "RELIANCE",
             *       "HDFCBANK",
             *       "INFY"
             *     ]
             */
            symbols?: string[] | null;
        };
        /** IngestResponse */
        IngestResponse: {
            /**
             * Job Id
             * @description Unique ingestion job execution ID
             */
            job_id: string;
            /**
             * Status
             * @description Job execution status (completed, partial, failed)
             */
            status: string;
            /**
             * Symbols Ingested
             * @description Number of symbols successfully processed
             */
            symbols_ingested: number;
            /**
             * Rows Ingested
             * @description Total new price rows inserted into database
             */
            rows_ingested: number;
            /**
             * Errors
             * @description List of non-fatal ingestion warnings or errors
             * @default []
             */
            errors: string[];
        };
        /** PriceItem */
        PriceItem: {
            /**
             * Date
             * @description Session date (YYYY-MM-DD)
             */
            date: string;
            /**
             * Open
             * @description Opening price
             */
            open: number;
            /**
             * High
             * @description Highest price during session
             */
            high: number;
            /**
             * Low
             * @description Lowest price during session
             */
            low: number;
            /**
             * Close
             * @description Unadjusted closing price
             */
            close: number;
            /**
             * Adj Close
             * @description Corporate-action adjusted closing price
             */
            adj_close: number;
            /**
             * Volume
             * @description Total trading volume
             */
            volume: number;
        };
        /** PricesResponse */
        PricesResponse: {
            /**
             * Symbol
             * @description Equity ticker symbol
             */
            symbol: string;
            /**
             * Count
             * @description Number of sessions returned
             */
            count: number;
            /**
             * Prices
             * @description Chronological series of OHLCV bars
             */
            prices: components["schemas"]["PriceItem"][];
        };
        /** UniverseResponse */
        UniverseResponse: {
            /**
             * Date
             * @description Target date for universe constituent evaluation
             */
            date: string;
            /**
             * Count
             * @description Total number of constituent tickers (ranks 101 to 750)
             */
            count: number;
            /**
             * Tickers
             * @description List of ticker symbols belonging to the universe
             */
            tickers: string[];
            /**
             * Survivorship Bias
             * @description True if fallback current list was used due to missing point-in-time constituent records
             */
            survivorship_bias: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    api_v1_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    api_ingest_data_api_v1_data_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_coverage_api_v1_data_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageResponse"];
                };
            };
        };
    };
    api_get_universe_api_v1_universe_get: {
        parameters: {
            query?: {
                /** @description Target date in YYYY-MM-DD format. Defaults to UTC today. */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_prices_api_v1_prices__symbol__get: {
        parameters: {
            query?: {
                /** @description Optional start date (YYYY-MM-DD) */
                start?: string | null;
                /** @description Optional end date (YYYY-MM-DD) */
                end?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_nifty_indicators_api_v1_indicators_nifty_get: {
        parameters: {
            query?: {
                /** @description Optional start date (YYYY-MM-DD) */
                start?: string | null;
                /** @description Optional end date (YYYY-MM-DD) */
                end?: string | null;
                /** @description Comma-separated list of EMA spans */
                spans?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_symbol_indicators_api_v1_indicators__symbol__get: {
        parameters: {
            query?: {
                /** @description Optional start date (YYYY-MM-DD) */
                start?: string | null;
                /** @description Optional end date (YYYY-MM-DD) */
                end?: string | null;
                /** @description Comma-separated list of EMA spans */
                spans?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_preview_indicators_api_v1_indicators_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndicatorPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
