/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service Health Check
         * @description Returns service operational status and version
         */
        get: operations["root_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API v1 Health Check
         * @description Returns the current operational status and version of the API.
         */
        get: operations["api_v1_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Market Data
         * @description Ingests historical OHLCV data for equities and universe.
         */
        post: operations["api_ingest_data_api_v1_data_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Data Coverage
         * @description Returns stored date ranges and session counts for symbols.
         */
        get: operations["api_get_coverage_api_v1_data_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Universe Constituents
         * @description Returns tickers ranked 101 to 750 with survivorship bias flag.
         */
        get: operations["api_get_universe_api_v1_universe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prices/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Symbol Prices
         * @description Returns historical OHLCV prices for symbol, filtered chronologically.
         */
        get: operations["api_get_prices_api_v1_prices__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indicators/nifty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get NIFTY Benchmark Indicators
         * @description Returns NIFTY benchmark index OHLCV with EMAs (default 50 and 200).
         */
        get: operations["api_get_nifty_indicators_api_v1_indicators_nifty_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indicators/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Symbol Technical Indicators
         * @description Returns historical OHLCV augmented with EMAs (20, 50, 150, 200) and 52W high.
         */
        get: operations["api_get_symbol_indicators_api_v1_indicators__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indicators/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Custom Indicators
         * @description Calculates custom indicators dynamically with given configuration.
         */
        post: operations["api_preview_indicators_api_v1_indicators_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals/screen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Screen Universe for Entry Signals
         * @description Returns point-in-time universe constituent symbols with an active entry signal on the given date (REQ-3.4).
         */
        get: operations["api_screen_signals_api_v1_signals_screen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Symbol Trading Signals
         * @description Returns chronological series of OHLCV bars with technical indicators, filters, and entry/exit signal evaluations (REQ-3.4, REQ-3.5).
         */
        get: operations["api_get_symbol_signals_api_v1_signals__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/size": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Position Size and Risk
         * @description Derives integer share quantity, capital required, stop loss price, and monetary risk amount based on corpus, entry price, stop loss %, and risk % (REQ-4.1, REQ-4.2, REQ-4.3).
         */
        post: operations["api_calculate_risk_size_api_v1_risk_size_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Default Risk Configuration
         * @description Returns baseline strategy risk, stop loss, capital, and cost parameters.
         */
        get: operations["api_get_risk_config_api_v1_risk_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Backtest Run
         * @description Asynchronously launches simulation in background task (REQ-5.4).
         */
        post: operations["api_run_backtest_api_v1_backtest_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest/sweep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Parameter Sweep
         * @description Generates permutation child runs across parameter grid and launches simulation (REQ-6.2).
         */
        post: operations["api_run_sweep_api_v1_backtest_sweep_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest/sweep/{sweep_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Parameter Sweep Status
         * @description Returns lifecycle status and summary metrics for all child runs in a sweep (REQ-6.2).
         */
        get: operations["api_get_sweep_status_api_v1_backtest_sweep__sweep_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare Multiple Backtest Runs
         * @description Returns aligned metrics table and overlaid equity curves for given run IDs (REQ-6.3).
         */
        get: operations["api_compare_backtest_runs_api_v1_backtest_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Backtest Runs
         * @description Returns chronological history of all executed backtests.
         */
        get: operations["api_list_backtest_runs_api_v1_backtest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Backtest Run Status
         * @description Returns execution status and summary metrics for a given run ID.
         */
        get: operations["api_get_backtest_status_api_v1_backtest__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest/{run_id}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Backtest Trade Ledger
         * @description Returns list of executed round-trip trades with PnL and exit reasons.
         */
        get: operations["api_get_backtest_trades_api_v1_backtest__run_id__trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest/{run_id}/equity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Backtest Equity Curve
         * @description Returns daily time-series of equity, cash, and drawdowns.
         */
        get: operations["api_get_backtest_equity_api_v1_backtest__run_id__equity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest/{run_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Backtest Run Audit Provenance
         * @description Returns audit and reproducibility provenance record for a backtest run (REQ-8.2), including Git commit SHA, config parameters, data snapshot hash, and library versions.
         */
        get: operations["api_get_backtest_audit_api_v1_backtest__run_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{run_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Backtest Run Performance Summary
         * @description Returns comprehensive core and advanced performance metrics (REQ-7.1).
         */
        get: operations["api_get_report_summary_api_v1_reports__run_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{run_id}/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Monthly Returns Matrix
         * @description Returns Month x Year compounded returns matrix (REQ-7.2).
         */
        get: operations["api_get_report_monthly_api_v1_reports__run_id__monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{run_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Backtest Report Bundle
         * @description Exports trade ledger and metrics bundle as CSV, XLSX, ZIP, or PDF (REQ-7.3, REQ-9.1, REQ-9.4).
         */
        get: operations["api_export_report_api_v1_reports__run_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{run_id}/export/pdf/async": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Force Asynchronous PDF Generation
         * @description Forces async background PDF generation regardless of trade count (REQ-9.4).
         */
        post: operations["api_export_pdf_async_api_v1_reports__run_id__export_pdf_async_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Asynchronous PDF Job Status
         * @description Returns lifecycle status and metadata for an async PDF generation job (REQ-9.4).
         */
        get: operations["api_get_pdf_job_status_api_v1_reports_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/jobs/{job_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Generated PDF From Async Job
         * @description Streams the generated PDF report when status is 'ready' (REQ-9.4).
         */
        get: operations["api_download_pdf_job_api_v1_reports_jobs__job_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{run_id}/preview.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview PDF First Page as PNG
         * @description Renders the first page of the PDF report as PNG for pre-download preview.
         */
        get: operations["api_get_pdf_preview_api_v1_reports__run_id__preview_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/validation/{run_id}/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get TradingView Cross-Check Data
         * @description Returns aligned indicators and entry/exit signals for manual visual diffing against TradingView (REQ-8.1). Supports JSON schema response or raw CSV file download via '?format=csv'.
         */
        get: operations["api_get_cross_check_api_v1_validation__run_id___symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacktestAuditResponse */
        BacktestAuditResponse: {
            /**
             * Run Id
             * @description Unique backtest run identifier
             */
            run_id: string;
            /**
             * Git Sha
             * @description Git commit hash of codebase during execution
             */
            git_sha: string;
            /**
             * Config
             * @description Strategy configuration parameters
             */
            config: {
                [key: string]: unknown;
            };
            /**
             * Data Hash
             * @description SHA-256 snapshot hash of input parquet market data
             */
            data_hash: string;
            /**
             * Versions
             * @description Runtime and library dependencies versions
             */
            versions: {
                [key: string]: string;
            };
            /**
             * Created At
             * @description Execution ISO timestamp
             */
            created_at?: string | null;
        };
        /** BacktestCompareResponse */
        BacktestCompareResponse: {
            /**
             * Run Ids
             * @description List of compared run IDs
             */
            run_ids: string[];
            /**
             * Runs
             * @description Summary metrics dictionary keyed by run_id
             */
            runs: {
                [key: string]: components["schemas"]["CompareMetricItem"];
            };
            /**
             * Equity Curves
             * @description Overlaid equity curves keyed by run_id
             */
            equity_curves?: {
                [key: string]: components["schemas"]["EquityPoint"][];
            };
        };
        /** BacktestConfigSchema */
        BacktestConfigSchema: {
            /**
             * Corpus
             * @description Starting portfolio corpus/capital in INR
             * @default 500000
             * @example 500000
             */
            corpus: number;
            /**
             * Capital
             * @description Starting portfolio capital in INR (alias for corpus)
             */
            capital?: number | null;
            /**
             * Risk Pct
             * @description Risk percentage per trade (default 0.02 = 2%)
             * @default 0.02
             * @example 0.02
             */
            risk_pct: number;
            /**
             * Stop Loss Pct
             * @description Stop loss percentage distance (default 0.07 = 7%)
             * @default 0.07
             * @example 0.07
             */
            stop_loss_pct: number;
            /**
             * Sl Pct
             * @description Stop loss percentage distance (alias for stop_loss_pct)
             */
            sl_pct?: number | null;
            /**
             * Lot Size
             * @description Minimum share lot multiple
             * @default 1
             * @example 1
             */
            lot_size: number;
            /**
             * Cost Bps
             * @description Transaction friction and slippage costs in basis points
             * @default 10
             * @example 10
             */
            cost_bps: number;
            /**
             * Ema Spans
             * @description Trend EMA spans
             * @default [
             *       20,
             *       50,
             *       150,
             *       200
             *     ]
             * @example [
             *       20,
             *       50,
             *       150,
             *       200
             *     ]
             */
            ema_spans: number[];
            /**
             * Regime Spans
             * @description NIFTY regime EMA spans
             * @default [
             *       50,
             *       200
             *     ]
             * @example [
             *       50,
             *       200
             *     ]
             */
            regime_spans: number[];
            /**
             * High 52W Factor
             * @description Proximity threshold to 52-week high
             * @default 0.85
             * @example 0.85
             */
            high_52w_factor: number;
            /**
             * High 52W Lookback
             * @description Lookback window sessions for 52W high
             * @default 252
             * @example 252
             */
            high_52w_lookback: number;
            /**
             * Allow Crossover Equal
             * @description Whether equality on bar T-1 satisfies crossover condition
             * @default false
             */
            allow_crossover_equal: boolean;
            /**
             * Ranking Rule
             * @description Candidate prioritization rule under capital constraints (momentum, alphabetical, 52w_proximity)
             * @default momentum
             * @example momentum
             */
            ranking_rule: string;
            /**
             * Universe Start Rank
             * @description Starting universe rank (inclusive)
             * @default 101
             * @example 101
             */
            universe_start_rank: number;
            /**
             * Universe End Rank
             * @description Ending universe rank (inclusive)
             * @default 750
             * @example 750
             */
            universe_end_rank: number;
        };
        /** BacktestEquityResponse */
        BacktestEquityResponse: {
            /**
             * Run Id
             * @description Unique backtest run identifier
             */
            run_id: string;
            /**
             * Count
             * @description Number of equity curve data points
             */
            count: number;
            /**
             * Equity Curve
             * @description Chronological daily mark-to-market equity curve
             */
            equity_curve: components["schemas"]["EquityPoint"][];
        };
        /** BacktestRunCreateResponse */
        BacktestRunCreateResponse: {
            /**
             * Run Id
             * @description Unique backtest run identifier
             */
            run_id: string;
            /**
             * Status
             * @description Initial lifecycle status (pending, running)
             * @default pending
             */
            status: string;
            /**
             * Message
             * @description Informational status message
             * @default Backtest execution queued
             */
            message: string;
        };
        /** BacktestRunRequest */
        BacktestRunRequest: {
            /**
             * Start
             * @description Optional backtest start date (YYYY-MM-DD)
             * @example 2020-06-01
             */
            start?: string | null;
            /**
             * End
             * @description Optional backtest end date (YYYY-MM-DD)
             * @example 2022-04-29
             */
            end?: string | null;
            /** @description Optional strategy parameter overrides */
            config?: components["schemas"]["BacktestConfigSchema"] | null;
            /**
             * Symbols
             * @description Optional subset of symbols (defaults to universe)
             * @example [
             *       "ALPHA",
             *       "BETA",
             *       "GAMMA"
             *     ]
             */
            symbols?: string[] | null;
        };
        /** BacktestStatusResponse */
        BacktestStatusResponse: {
            /**
             * Run Id
             * @description Unique backtest run identifier
             */
            run_id: string;
            /**
             * Status
             * @description Current lifecycle status (pending, running, completed, failed)
             */
            status: string;
            /**
             * Created At
             * @description Creation ISO timestamp
             */
            created_at: string;
            /**
             * Start Date
             * @description Start date
             */
            start_date?: string | null;
            /**
             * End Date
             * @description End date
             */
            end_date?: string | null;
            /**
             * Config Version
             * @description Configuration schema version
             * @default 1.0
             */
            config_version: string;
            /**
             * Sweep Id
             * @description Parent parameter sweep ID if applicable
             */
            sweep_id?: string | null;
            /**
             * Initial Capital
             * @description Starting capital in INR
             */
            initial_capital: number;
            /**
             * Final Capital
             * @description Ending capital in INR
             */
            final_capital?: number | null;
            /**
             * Total Return Pct
             * @description Total portfolio return percentage
             */
            total_return_pct?: number | null;
            /**
             * Cagr
             * @description Compound Annual Growth Rate
             */
            cagr?: number | null;
            /**
             * Total Trades
             * @description Total closed round-trip trades
             */
            total_trades?: number | null;
            /**
             * Win Rate
             * @description Fraction of winning trades
             */
            win_rate?: number | null;
            /**
             * Max Drawdown Pct
             * @description Maximum percentage drawdown
             */
            max_drawdown_pct?: number | null;
            /**
             * Error Message
             * @description Error explanation if failed
             */
            error_message?: string | null;
        };
        /** BacktestTradesResponse */
        BacktestTradesResponse: {
            /**
             * Run Id
             * @description Unique backtest run identifier
             */
            run_id: string;
            /**
             * Count
             * @description Total number of closed trades
             */
            count: number;
            /**
             * Trades
             * @description Chronological trade ledger
             */
            trades: components["schemas"]["TradeItem"][];
        };
        /** CompareMetricItem */
        CompareMetricItem: {
            /**
             * Run Id
             * @description Run identifier
             */
            run_id: string;
            /**
             * Status
             * @description Run status
             */
            status: string;
            /**
             * Config
             * @description Configuration parameters
             */
            config?: {
                [key: string]: unknown;
            };
            /**
             * Initial Capital
             * @description Starting capital
             */
            initial_capital: number;
            /**
             * Final Capital
             * @description Ending capital
             */
            final_capital?: number | null;
            /**
             * Total Return Pct
             * @description Total return percentage
             */
            total_return_pct?: number | null;
            /**
             * Cagr
             * @description Compound Annual Growth Rate
             */
            cagr?: number | null;
            /**
             * Total Trades
             * @description Total trades count
             */
            total_trades?: number | null;
            /**
             * Win Rate
             * @description Win rate
             */
            win_rate?: number | null;
            /**
             * Max Drawdown Pct
             * @description Max percentage drawdown
             */
            max_drawdown_pct?: number | null;
            /**
             * Avg Profit
             * @description Average profit on winning trades
             */
            avg_profit?: number | null;
            /**
             * Avg Loss
             * @description Average loss on losing trades
             */
            avg_loss?: number | null;
        };
        /** ConstituentDetail */
        ConstituentDetail: {
            /**
             * Symbol
             * @description Equity ticker symbol
             */
            symbol: string;
            /**
             * Name
             * @description Human-readable company name
             */
            name: string;
            /**
             * Rank
             * @description Market capitalization rank (101 to 750)
             */
            rank: number;
            /**
             * Sector
             * @description Industry or sector classification
             * @default Diversified
             */
            sector: string;
        };
        /** CoverageItem */
        CoverageItem: {
            /**
             * Symbol
             * @description Equity or index ticker symbol
             */
            symbol: string;
            /**
             * First Date
             * @description Earliest available trading session
             */
            first_date?: string | null;
            /**
             * Last Date
             * @description Latest available trading session
             */
            last_date?: string | null;
            /**
             * Rows
             * @description Total number of stored trading sessions
             */
            rows: number;
        };
        /** CoverageResponse */
        CoverageResponse: {
            /**
             * Items
             * @description List of symbol coverage summaries
             */
            items: components["schemas"]["CoverageItem"][];
        };
        /** CrossCheckPoint */
        CrossCheckPoint: {
            /**
             * Date
             * @description Session date (YYYY-MM-DD)
             */
            date: string;
            /**
             * Close
             * @description Price used for indicators and evaluation
             */
            close: number;
            /**
             * Ema 20
             * @description 20-day Exponential Moving Average
             */
            ema_20?: number | null;
            /**
             * Ema 50
             * @description 50-day Exponential Moving Average
             */
            ema_50?: number | null;
            /**
             * Ema 150
             * @description 150-day Exponential Moving Average
             */
            ema_150?: number | null;
            /**
             * Ema 200
             * @description 200-day Exponential Moving Average
             */
            ema_200?: number | null;
            /**
             * High 52W
             * @description 252-day rolling 52-week high
             */
            high_52w?: number | null;
            /**
             * Entry
             * @description Whether entry signal triggered on this session
             */
            entry: boolean;
            /**
             * Exit
             * @description Whether exit signal triggered on this session
             */
            exit: boolean;
        };
        /** CrossCheckResponse */
        CrossCheckResponse: {
            /**
             * Run Id
             * @description Backtest run identifier
             */
            run_id: string;
            /**
             * Symbol
             * @description NSE equity ticker symbol
             */
            symbol: string;
            /**
             * Count
             * @description Total trading sessions returned
             */
            count: number;
            /**
             * Rows
             * @description Aligned indicator and signal data rows
             */
            rows: components["schemas"]["CrossCheckPoint"][];
            /**
             * Csv
             * @description Raw CSV string formatted for TradingView visual diff
             */
            csv: string;
        };
        /** EquityPoint */
        EquityPoint: {
            /**
             * Date
             * @description Session date (YYYY-MM-DD)
             */
            date: string;
            /**
             * Equity
             * @description Total mark-to-market equity
             */
            equity: number;
            /**
             * Cash
             * @description Available cash balance
             */
            cash: number;
            /**
             * Positions Value
             * @description Open positions market value
             */
            positions_value: number;
            /**
             * Open Positions
             * @description Number of currently held positions
             */
            open_positions: number;
            /**
             * Daily Return
             * @description Day-over-day return fraction
             */
            daily_return: number;
            /**
             * Drawdown
             * @description Drawdown from equity peak in INR
             */
            drawdown: number;
            /**
             * Drawdown Pct
             * @description Drawdown percentage from peak
             */
            drawdown_pct: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description Operational status of the service
             * @default ok
             * @example ok
             */
            status: string;
            /**
             * Version
             * @description Semantic application version
             * @default 0.1.0
             * @example 0.1.0
             */
            version: string;
        };
        /** IndicatorConfigSchema */
        IndicatorConfigSchema: {
            /**
             * Spans
             * @description EMA spans to compute (e.g. [20, 50, 150, 200])
             * @default [
             *       20,
             *       50,
             *       150,
             *       200
             *     ]
             * @example [
             *       20,
             *       50,
             *       150,
             *       200
             *     ]
             */
            spans: number[];
            /**
             * Include High 52W
             * @description Whether to compute rolling 52-week high
             * @default true
             */
            include_high_52w: boolean;
            /**
             * High 52W Lookback
             * @description Lookback window sessions for 52W high calculation
             * @default 252
             * @example 252
             */
            high_52w_lookback: number;
        };
        /** IndicatorItem */
        IndicatorItem: {
            /**
             * Date
             * @description Session date (YYYY-MM-DD)
             */
            date: string;
            /**
             * Open
             * @description Opening price
             */
            open: number;
            /**
             * High
             * @description Highest price during session
             */
            high: number;
            /**
             * Low
             * @description Lowest price during session
             */
            low: number;
            /**
             * Close
             * @description Unadjusted closing price
             */
            close: number;
            /**
             * Adj Close
             * @description Corporate-action adjusted closing price
             */
            adj_close: number;
            /**
             * Volume
             * @description Total trading volume
             */
            volume: number;
            /**
             * Ema 20
             * @description 20-day EMA
             */
            ema_20?: number | null;
            /**
             * Ema 50
             * @description 50-day EMA
             */
            ema_50?: number | null;
            /**
             * Ema 150
             * @description 150-day EMA
             */
            ema_150?: number | null;
            /**
             * Ema 200
             * @description 200-day EMA
             */
            ema_200?: number | null;
            /**
             * High 52W
             * @description 52-week rolling high
             */
            high_52w?: number | null;
            /**
             * Indicators
             * @description Dictionary of dynamic or custom computed indicator values
             */
            indicators?: {
                [key: string]: number | null;
            };
        };
        /** IndicatorPreviewRequest */
        IndicatorPreviewRequest: {
            /**
             * Symbol
             * @description Symbol to compute preview indicators for
             * @default RELIANCE
             * @example RELIANCE
             */
            symbol: string;
            /**
             * Start
             * @description Optional start date (YYYY-MM-DD)
             * @example 2020-01-01
             */
            start?: string | null;
            /**
             * End
             * @description Optional end date (YYYY-MM-DD)
             * @example 2023-12-31
             */
            end?: string | null;
            /** @description Indicator calculation configuration */
            config?: components["schemas"]["IndicatorConfigSchema"];
        };
        /** IndicatorResponse */
        IndicatorResponse: {
            /**
             * Symbol
             * @description Equity or benchmark ticker symbol
             */
            symbol: string;
            /**
             * Count
             * @description Number of indicator bars returned
             */
            count: number;
            /**
             * Indicators
             * @description Chronological series of indicator-augmented OHLCV bars
             */
            indicators: components["schemas"]["IndicatorItem"][];
        };
        /** IngestRequest */
        IngestRequest: {
            /**
             * Start
             * @description Start date for data ingestion in YYYY-MM-DD format
             * @example 2020-01-01
             */
            start: string;
            /**
             * End
             * @description End date for data ingestion in YYYY-MM-DD format
             * @example 2024-01-01
             */
            end: string;
            /**
             * Symbols
             * @description Optional list of ticker symbols. Defaults to active universe.
             * @example [
             *       "RELIANCE",
             *       "HDFCBANK",
             *       "INFY"
             *     ]
             */
            symbols?: string[] | null;
        };
        /** IngestResponse */
        IngestResponse: {
            /**
             * Job Id
             * @description Unique ingestion job execution ID
             */
            job_id: string;
            /**
             * Status
             * @description Job execution status (completed, partial, failed)
             */
            status: string;
            /**
             * Symbols Ingested
             * @description Number of symbols successfully processed
             */
            symbols_ingested: number;
            /**
             * Rows Ingested
             * @description Total new price rows inserted into database
             */
            rows_ingested: number;
            /**
             * Errors
             * @description List of non-fatal ingestion warnings or errors
             * @default []
             */
            errors: string[];
        };
        /** MonthlyReturnRow */
        MonthlyReturnRow: {
            /**
             * Year
             * @description Calendar year
             */
            year: number;
            /**
             * Jan
             * @description January compounded return
             */
            jan?: number | null;
            /**
             * Feb
             * @description February compounded return
             */
            feb?: number | null;
            /**
             * Mar
             * @description March compounded return
             */
            mar?: number | null;
            /**
             * Apr
             * @description April compounded return
             */
            apr?: number | null;
            /**
             * May
             * @description May compounded return
             */
            may?: number | null;
            /**
             * Jun
             * @description June compounded return
             */
            jun?: number | null;
            /**
             * Jul
             * @description July compounded return
             */
            jul?: number | null;
            /**
             * Aug
             * @description August compounded return
             */
            aug?: number | null;
            /**
             * Sep
             * @description September compounded return
             */
            sep?: number | null;
            /**
             * Oct
             * @description October compounded return
             */
            oct?: number | null;
            /**
             * Nov
             * @description November compounded return
             */
            nov?: number | null;
            /**
             * Dec
             * @description December compounded return
             */
            dec?: number | null;
            /**
             * Total
             * @description Full year compounded return
             */
            total: number;
        };
        /**
         * PdfJobCreateResponse
         * @description Response returned when initiating an asynchronous PDF generation job.
         *
         *     Covers REQ-9.4.
         */
        PdfJobCreateResponse: {
            /**
             * Job Id
             * @description Unique background PDF generation job ID
             */
            job_id: string;
            /**
             * Status
             * @description Initial job status
             * @default pending
             */
            status: string;
            /**
             * Message
             * @description Informational status message
             * @default PDF generation job accepted and processing in background.
             */
            message: string;
        };
        /**
         * PdfJobResponse
         * @description Status record of an asynchronous PDF generation background job (REQ-9.4).
         */
        PdfJobResponse: {
            /**
             * Job Id
             * @description Unique background PDF generation job ID
             */
            job_id: string;
            /**
             * Status
             * @description Job status: 'pending', 'ready', or 'failed'
             */
            status: string;
            /**
             * File Path
             * @description Absolute file path to ready PDF on server
             */
            file_path?: string | null;
            /**
             * Error
             * @description Error message if generation failed
             */
            error?: string | null;
            /**
             * Created At
             * @description Job creation ISO timestamp
             */
            created_at: string;
        };
        /**
         * PerformanceMetrics
         * @description Container holding core and advanced quantitative strategy performance metrics.
         */
        PerformanceMetrics: {
            /**
             * Total Trades
             * @description Total completed round-trip trades
             */
            total_trades: number;
            /**
             * Win Trades
             * @description Number of profitable trades (PnL > 0)
             */
            win_trades: number;
            /**
             * Loss Trades
             * @description Number of losing or scratch trades (PnL <= 0)
             */
            loss_trades: number;
            /**
             * Win Rate
             * @description Fraction of winning trades (0.0 to 1.0, 4 decimal places)
             */
            win_rate: number;
            /**
             * Avg Profit
             * @description Average profit of winning trades in INR (2 decimal places)
             */
            avg_profit: number;
            /**
             * Avg Loss
             * @description Average loss of losing trades in INR (2 decimal places)
             */
            avg_loss: number;
            /**
             * Total Return Pct
             * @description Total percentage return (4 decimal places)
             */
            total_return_pct: number;
            /**
             * Initial Capital
             * @description Initial starting corpus in INR (2 decimal places)
             */
            initial_capital: number;
            /**
             * Final Capital
             * @description Ending portfolio equity in INR (2 decimal places)
             */
            final_capital: number;
            /**
             * Net Profit
             * @description Net portfolio monetary gain/loss in INR (2 decimal places)
             */
            net_profit: number;
            /**
             * Cagr
             * @description Compound Annual Growth Rate (4 decimal places)
             */
            cagr: number;
            /**
             * Max Drawdown Pct
             * @description Maximum peak-to-trough percentage drawdown (4 decimal places)
             */
            max_drawdown_pct: number;
            /**
             * Max Drawdown Amount
             * @description Maximum peak-to-trough monetary drawdown in INR (2 decimal places)
             */
            max_drawdown_amount: number;
            /**
             * Sharpe Ratio
             * @description Annualized Sharpe Ratio with rf=0 (4 decimal places)
             */
            sharpe_ratio: number;
            /**
             * Sortino Ratio
             * @description Annualized Sortino Ratio with MAR=0 (4 decimal places)
             */
            sortino_ratio: number;
            /**
             * Calmar Ratio
             * @description Calmar Ratio: CAGR / Max Drawdown (4 decimal places)
             */
            calmar_ratio: number;
            /**
             * Profit Factor
             * @description Gross Profits / Gross Losses (4 decimal places)
             */
            profit_factor: number;
            /**
             * Expectancy
             * @description Average monetary expectancy per trade in INR (2 decimal places)
             */
            expectancy: number;
            /**
             * Avg Days Held
             * @description Average holding duration in days (1 decimal place)
             */
            avg_days_held: number;
        };
        /** PriceItem */
        PriceItem: {
            /**
             * Date
             * @description Session date (YYYY-MM-DD)
             */
            date: string;
            /**
             * Open
             * @description Opening price
             */
            open: number;
            /**
             * High
             * @description Highest price during session
             */
            high: number;
            /**
             * Low
             * @description Lowest price during session
             */
            low: number;
            /**
             * Close
             * @description Unadjusted closing price
             */
            close: number;
            /**
             * Adj Close
             * @description Corporate-action adjusted closing price
             */
            adj_close: number;
            /**
             * Volume
             * @description Total trading volume
             */
            volume: number;
        };
        /** PricesResponse */
        PricesResponse: {
            /**
             * Symbol
             * @description Equity ticker symbol
             */
            symbol: string;
            /**
             * Count
             * @description Number of sessions returned
             */
            count: number;
            /**
             * Prices
             * @description Chronological series of OHLCV bars
             */
            prices: components["schemas"]["PriceItem"][];
        };
        /** ReportMonthlyResponse */
        ReportMonthlyResponse: {
            /**
             * Run Id
             * @description Unique backtest run identifier
             */
            run_id: string;
            /**
             * Years
             * @description Month x year returns matrix
             */
            years: components["schemas"]["MonthlyReturnRow"][];
        };
        /** ReportSummaryResponse */
        ReportSummaryResponse: {
            /**
             * Run Id
             * @description Unique backtest run identifier
             */
            run_id: string;
            /**
             * Status
             * @description Execution status
             */
            status: string;
            /**
             * Created At
             * @description ISO 8601 creation timestamp
             */
            created_at: string;
            /**
             * Config
             * @description Strategy parameters
             */
            config?: {
                [key: string]: unknown;
            };
            /** @description Calculated core and advanced KPIs */
            metrics: components["schemas"]["PerformanceMetrics"];
        };
        /** RiskConfigResponse */
        RiskConfigResponse: {
            /**
             * Corpus
             * @description Default portfolio starting corpus in INR
             * @default 500000
             */
            corpus: number;
            /**
             * Risk Pct
             * @description Default risk percentage per trade (2%)
             * @default 0.02
             */
            risk_pct: number;
            /**
             * Stop Loss Pct
             * @description Default stop loss percentage (7%)
             * @default 0.07
             */
            stop_loss_pct: number;
            /**
             * Lot Size
             * @description Default share lot size multiple (1)
             * @default 1
             */
            lot_size: number;
            /**
             * Cost Bps
             * @description Default transaction friction and slippage costs in basis points (10 bps = 0.10%)
             * @default 10
             */
            cost_bps: number;
        };
        /** RiskSizeRequest */
        RiskSizeRequest: {
            /**
             * Corpus
             * @description Total account capital / portfolio corpus
             * @example 500000
             */
            corpus: number;
            /**
             * Entry
             * @description Proposed trade entry price per share
             * @example 100
             */
            entry: number;
            /**
             * Sl Pct
             * @description Stop loss percentage distance from entry (default 0.07)
             * @default 0.07
             * @example 0.07
             */
            sl_pct: number;
            /**
             * Risk Pct
             * @description Maximum account risk percentage per trade (default 0.02)
             * @default 0.02
             * @example 0.02
             */
            risk_pct: number;
            /**
             * Lot Size
             * @description Minimum lot size multiple (default 1)
             * @default 1
             * @example 1
             */
            lot_size: number;
        };
        /** RiskSizeResponse */
        RiskSizeResponse: {
            /**
             * Qty
             * @description Derived integer position size / share quantity
             */
            qty: number;
            /**
             * Capital Required
             * @description Total capital required for this position (qty * entry)
             */
            capital_required: number;
            /**
             * Sl Price
             * @description Stop loss price level (entry * (1 - sl_pct))
             */
            sl_price: number;
            /**
             * Risk Amount
             * @description Maximum monetary account risk for this trade (corpus * risk_pct)
             */
            risk_amount: number;
        };
        /** ScreenResponse */
        ScreenResponse: {
            /**
             * Date
             * @description Target date for universe screening (YYYY-MM-DD)
             */
            date: string;
            /**
             * Count
             * @description Total number of constituent tickers with entry signal
             */
            count: number;
            /**
             * Symbols
             * @description List of ticker symbols with active entry signals
             */
            symbols: string[];
            /**
             * Survivorship Bias
             * @description True if fallback current list was used due to missing point-in-time constituent records
             */
            survivorship_bias: boolean;
        };
        /** SignalItem */
        SignalItem: {
            /**
             * Date
             * @description Session date (YYYY-MM-DD)
             */
            date: string;
            /**
             * Open
             * @description Opening price
             */
            open: number;
            /**
             * High
             * @description Highest price during session
             */
            high: number;
            /**
             * Low
             * @description Lowest price during session
             */
            low: number;
            /**
             * Close
             * @description Unadjusted closing price
             */
            close: number;
            /**
             * Adj Close
             * @description Corporate-action adjusted closing price
             */
            adj_close: number;
            /**
             * Volume
             * @description Total trading volume
             */
            volume: number;
            /**
             * Ema 20
             * @description 20-day EMA
             */
            ema_20?: number | null;
            /**
             * Ema 50
             * @description 50-day EMA
             */
            ema_50?: number | null;
            /**
             * Ema 150
             * @description 150-day EMA
             */
            ema_150?: number | null;
            /**
             * Ema 200
             * @description 200-day EMA
             */
            ema_200?: number | null;
            /**
             * High 52W
             * @description 52-week rolling high
             */
            high_52w?: number | null;
            /**
             * Regime Ok
             * @description Market regime filter (NIFTY Close > EMA 50 & EMA 200)
             */
            regime_ok: boolean;
            /**
             * Trend Ok
             * @description Stock trend filter (EMA 20 > EMA 50 > EMA 150 > EMA 200)
             */
            trend_ok: boolean;
            /**
             * Near 52W High
             * @description 52W high proximity filter (Close > 0.85 * 52W High)
             */
            near_52w_high: boolean;
            /**
             * Crossover
             * @description EMA20 crossover trigger (Close_T > EMA20_T and Close_T-1 < EMA20_T-1)
             */
            crossover: boolean;
            /**
             * Entry
             * @description Entry signal triggered on bar T for execution on T+1 open
             */
            entry: boolean;
            /**
             * Exit
             * @description Exit signal triggered on bar T (Close_T < EMA20_T)
             */
            exit: boolean;
        };
        /** SignalsResponse */
        SignalsResponse: {
            /**
             * Symbol
             * @description Equity ticker symbol
             */
            symbol: string;
            /**
             * Count
             * @description Number of signal rows returned
             */
            count: number;
            /**
             * Signals
             * @description Chronological series of signal-augmented OHLCV bars
             */
            signals: components["schemas"]["SignalItem"][];
        };
        /** SweepRunCreateResponse */
        SweepRunCreateResponse: {
            /**
             * Sweep Id
             * @description Unique parameter sweep identifier
             */
            sweep_id: string;
            /**
             * Total Runs
             * @description Total permutation child runs generated
             */
            total_runs: number;
            /**
             * Run Ids
             * @description List of generated child run IDs
             */
            run_ids: string[];
            /**
             * Status
             * @description Initial lifecycle status
             * @default pending
             */
            status: string;
            /**
             * Message
             * @description Informational status message
             * @default Parameter sweep execution queued successfully
             */
            message: string;
        };
        /** SweepRunItem */
        SweepRunItem: {
            /**
             * Run Id
             * @description Child run ID
             */
            run_id: string;
            /**
             * Status
             * @description Child run lifecycle status
             */
            status: string;
            /**
             * Params
             * @description Parameter values for this specific run
             */
            params?: {
                [key: string]: unknown;
            };
            /**
             * Initial Capital
             * @description Starting capital
             */
            initial_capital: number;
            /**
             * Final Capital
             * @description Ending capital
             */
            final_capital?: number | null;
            /**
             * Total Return Pct
             * @description Total return percentage
             */
            total_return_pct?: number | null;
            /**
             * Total Trades
             * @description Total trades count
             */
            total_trades?: number | null;
            /**
             * Win Rate
             * @description Win rate
             */
            win_rate?: number | null;
            /**
             * Max Drawdown Pct
             * @description Maximum drawdown percentage
             */
            max_drawdown_pct?: number | null;
            /**
             * Cagr
             * @description Compound Annual Growth Rate
             */
            cagr?: number | null;
            /**
             * Error Message
             * @description Error message if failed
             */
            error_message?: string | null;
        };
        /** SweepRunRequest */
        SweepRunRequest: {
            /** @description Optional base strategy configuration template */
            base_config?: components["schemas"]["BacktestConfigSchema"] | null;
            /**
             * Param Grid
             * @description Map of parameter names to lists of candidate values to sweep
             * @example {
             *       "risk_pct": [
             *         0.01,
             *         0.02,
             *         0.03
             *       ],
             *       "sl_pct": [
             *         0.05,
             *         0.06,
             *         0.07
             *       ]
             *     }
             */
            param_grid: {
                [key: string]: unknown[];
            };
            /**
             * Start
             * @description Optional backtest start date (YYYY-MM-DD)
             * @example 2020-06-01
             */
            start?: string | null;
            /**
             * End
             * @description Optional backtest end date (YYYY-MM-DD)
             * @example 2022-04-29
             */
            end?: string | null;
            /**
             * Symbols
             * @description Optional subset of symbols (defaults to universe)
             * @example [
             *       "ALPHA",
             *       "BETA",
             *       "GAMMA"
             *     ]
             */
            symbols?: string[] | null;
        };
        /** SweepStatusResponse */
        SweepStatusResponse: {
            /**
             * Sweep Id
             * @description Unique sweep identifier
             */
            sweep_id: string;
            /**
             * Status
             * @description Overall sweep status (pending, running, completed, partial, failed)
             */
            status: string;
            /**
             * Created At
             * @description Creation ISO timestamp
             */
            created_at: string;
            /**
             * Param Grid
             * @description Parameters swept
             */
            param_grid?: {
                [key: string]: unknown[];
            };
            /**
             * Total Runs
             * @description Total permutation runs
             */
            total_runs: number;
            /**
             * Completed Runs
             * @description Number of completed runs so far
             */
            completed_runs: number;
            /**
             * Runs
             * @description Summary metrics for each child run
             */
            runs: components["schemas"]["SweepRunItem"][];
        };
        /** TradeItem */
        TradeItem: {
            /**
             * Symbol
             * @description Equity ticker symbol
             */
            symbol: string;
            /**
             * Entry Date
             * @description Entry date (YYYY-MM-DD)
             */
            entry_date: string;
            /**
             * Entry Price
             * @description Execution buy price with slippage
             */
            entry_price: number;
            /**
             * Qty
             * @description Executed share quantity
             */
            qty: number;
            /**
             * Exit Date
             * @description Exit date (YYYY-MM-DD)
             */
            exit_date: string;
            /**
             * Exit Price
             * @description Execution sell price with slippage
             */
            exit_price: number;
            /**
             * Pnl
             * @description Net realized profit/loss in INR
             */
            pnl: number;
            /**
             * Pnl Pct
             * @description Net realized return percentage
             */
            pnl_pct: number;
            /**
             * Exit Reason
             * @description Exit reason: stop_loss, gap, exit_signal
             */
            exit_reason: string;
            /**
             * Days Held
             * @description Trading sessions held
             */
            days_held: number;
            /**
             * Costs
             * @description Total friction costs in INR
             */
            costs: number;
        };
        /** UniverseResponse */
        UniverseResponse: {
            /**
             * Date
             * @description Target date for universe constituent evaluation
             */
            date: string;
            /**
             * Count
             * @description Total number of constituent tickers (ranks 101 to 750)
             */
            count: number;
            /**
             * Tickers
             * @description List of ticker symbols belonging to the universe
             */
            tickers: string[];
            /**
             * Details
             * @description Constituent stock metadata including company name, rank, and sector
             */
            details?: components["schemas"]["ConstituentDetail"][];
            /**
             * Survivorship Bias
             * @description True if fallback current list was used due to missing point-in-time constituent records
             */
            survivorship_bias: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    api_v1_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    api_ingest_data_api_v1_data_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_coverage_api_v1_data_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageResponse"];
                };
            };
        };
    };
    api_get_universe_api_v1_universe_get: {
        parameters: {
            query?: {
                /** @description Target date in YYYY-MM-DD format. Defaults to UTC today. */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_prices_api_v1_prices__symbol__get: {
        parameters: {
            query?: {
                /** @description Optional start date (YYYY-MM-DD) */
                start?: string | null;
                /** @description Optional end date (YYYY-MM-DD) */
                end?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_nifty_indicators_api_v1_indicators_nifty_get: {
        parameters: {
            query?: {
                /** @description Optional start date (YYYY-MM-DD) */
                start?: string | null;
                /** @description Optional end date (YYYY-MM-DD) */
                end?: string | null;
                /** @description Comma-separated list of EMA spans */
                spans?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_symbol_indicators_api_v1_indicators__symbol__get: {
        parameters: {
            query?: {
                /** @description Optional start date (YYYY-MM-DD) */
                start?: string | null;
                /** @description Optional end date (YYYY-MM-DD) */
                end?: string | null;
                /** @description Comma-separated list of EMA spans */
                spans?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_preview_indicators_api_v1_indicators_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndicatorPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_screen_signals_api_v1_signals_screen_get: {
        parameters: {
            query: {
                /** @description Target evaluation date in YYYY-MM-DD format */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_symbol_signals_api_v1_signals__symbol__get: {
        parameters: {
            query?: {
                /** @description Optional start date (YYYY-MM-DD) */
                start?: string | null;
                /** @description Optional end date (YYYY-MM-DD) */
                end?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_calculate_risk_size_api_v1_risk_size_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskSizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskSizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_risk_config_api_v1_risk_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskConfigResponse"];
                };
            };
        };
    };
    api_run_backtest_api_v1_backtest_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_run_sweep_api_v1_backtest_sweep_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SweepRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SweepRunCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_sweep_status_api_v1_backtest_sweep__sweep_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sweep_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SweepStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_compare_backtest_runs_api_v1_backtest_compare_get: {
        parameters: {
            query: {
                run_ids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestCompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_list_backtest_runs_api_v1_backtest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestStatusResponse"][];
                };
            };
        };
    };
    api_get_backtest_status_api_v1_backtest__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_backtest_trades_api_v1_backtest__run_id__trades_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestTradesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_backtest_equity_api_v1_backtest__run_id__equity_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestEquityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_backtest_audit_api_v1_backtest__run_id__audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestAuditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_report_summary_api_v1_reports__run_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_report_monthly_api_v1_reports__run_id__monthly_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportMonthlyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_export_report_api_v1_reports__run_id__export_get: {
        parameters: {
            query?: {
                /** @description Export format: 'csv' (trade ledger), 'xlsx' (Excel workbook), 'zip' (all CSVs), or 'pdf' (print-ready PDF) */
                format?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_export_pdf_async_api_v1_reports__run_id__export_pdf_async_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PdfJobCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_pdf_job_status_api_v1_reports_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PdfJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_download_pdf_job_api_v1_reports_jobs__job_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_pdf_preview_api_v1_reports__run_id__preview_png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_cross_check_api_v1_validation__run_id___symbol__get: {
        parameters: {
            query?: {
                /** @description Response format: 'json' (default) or 'csv' (file attachment) */
                format?: string;
            };
            header?: never;
            path: {
                run_id: string;
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrossCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
